[package]
name = "no-time-reset-on-death"
version = "1.0.0"
edition = "2024"

[dependencies]
fromsoftware-shared = { git = "https://github.com/vswarte/fromsoftware-rs.git" }
eldenring = { git = "https://github.com/vswarte/fromsoftware-rs.git" }

[lib]
crate-type = ["cdylib"]